---
- name: Install PHP Dependencies
  apt:
    name:
    - software-properties-common
    state: present
    
- name: Add OndreJ PHP Repo
  shell: LC_ALL=en_us.UTF-b add-apt-repository ppa:ondrej/php -y
     
- name: Update Apt Cache
  apt: update_cache=yes
     
- name: Install PHP 5.0
  apt: 
    name :
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - php5-curl
    - php5-json 
    state: present
 
- name: Restart Apache2
  service: name=apache2 state=restarted

- name: Create PHP Info File
  lineinfile: dest=/var/www/html/phpinfo.php
    regexp='^'
    line='<?php phpinfo(); \n?>'
    create=true
    state=present  
  
